### ISSUE TITLE
Trad

### ISSUE THREAD

**Issue by darktweek** [StarCitizenWiki/discord-bot#23]
Hi !

I very like your project.
Is there a way to get in English or French ?

Thanks

**Comment by octfx** [comment]
We could add english relatively easy. I'll have a look to how long it would take :)

**Comment by darktweek** [comment]
It would be great 😃

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by octfx** [comment]
So after quite some time, I've got the first localization pass implemented on the bot!

Bot commands are now localized based on the client locale.  
The localization files can be found here: https://github.com/StarCitizenWiki/discord-bot/tree/master/i18n

And the localization data for all commands can be found directly in the command files https://github.com/StarCitizenWiki/discord-bot/tree/master/src/commands
